on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test that we can use the htaccess tester
    steps:
    - name: Add a very basic htaccess file
      run: echo "RewriteRule .* /foo" >> .htaccess
    - name: Test that we can run this action
      uses: madewithlove/htaccess-cli-github-action@main
      with:
        url: http://localhost
        expected-url: http://localhost/foo

  test-failure:
    runs-on: ubuntu-latest
    name: Test that we can let a pipeline fail
    steps:
    - name: Add a very basic htaccess file
      run: echo "RewriteRule .* /foo" >> .htaccess
    - name: Test that we can run this action
      uses: madewithlove/htaccess-cli-github-action@main
      with:
        url: http://localhost
        expected-url: http://localhost/bar
      continue-on-error: true

  test-multiple-urls:
    runs-on: ubuntu-latest
    name: Test that multiple urls can be used
    steps:
    - name: Add a very basic htaccess file
      run: echo "RewriteRule .* /foo" >> .htaccess
    - name: Add an url-list file
      run: |
        echo "http://localhost/test: http://localhost/foo" >> url-list.yml
        echo "http://localhost/bar: http://localhost/foo" >> url-list.yml
    - name: Test that we can run this action
      uses: madewithlove/htaccess-cli-github-action@multiple
      with:
        url-list: url-list.yml

  test-multiple-urls-failure:
    runs-on: ubuntu-latest
    name: Test that multiple urls failure works
    steps:
    - name: Add a very basic htaccess file
      run: echo "RewriteRule .* /foo" >> .htaccess
    - name: Add an url-list file
      run: |
        echo "http://localhost/test: http://localhost/foo" >> url-list.yml
        echo "http://localhost/bar: http://localhost/wrong" >> url-list.yml
    - name: Test that we can run this action
      uses: madewithlove/htaccess-cli-github-action@multiple
      with:
        url-list: url-list.yml
      continue-on-error: true
